# **NumPy Cheat Sheet — Quick Reference with Examples**

This notebook contains a concise NumPy reference with runnable examples.

In [17]:
# Import convention
import numpy as np
print('NumPy imported, version:', np.__version__)

NumPy imported, version: 2.1.0


## **Contents**
- Introduction
- Creating arrays
- Array attributes
- Indexing & slicing
- Fancy & boolean indexing
- Shape manipulation
- Stacking & splitting
- Broadcasting
- Universal functions (ufuncs)
- Aggregations & statistics
- Random module
- Linear algebra
- Sorting & unique
- Data types
- File I/O
- Performance tips
- Examples & Practice questions

---

## **Introduction**

NumPy is the fundamental package for scientific computing in Python. It provides the `ndarray`: a fast, memory-efficient multidimensional array.

Import convention:


In [1]:
import numpy as np

## **Creating arrays**

- From Python lists:

In [15]:
a=np.array([1,2,3])
M=np.array([[1,2],[3,4]])

- Special arrays:

In [14]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))
eye = np.eye(3)                # identity matrix
empty = np.empty((2,2))        # uninitialized
ar = np.arange(0, 10, 2)       # like range
lin = np.linspace(0, 1, 5)     # 5 evenly spaced points

- From functions:

In [16]:
np.fromfunction(lambda i, j: i + j, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## **Array attributes**

- Shape, size, ndim, dtype:

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape    # (2, 3)
arr.size     # 6
arr.ndim     # 2
arr.dtype    # dtype('int64') (platform-dependent)

dtype('int64')

## **Indexing & slicing**

- Basic indexing/slicing is like Python lists but per-axis:

In [24]:

x = np.arange(10)
x[2:8:2]    # slice with step
M = np.arange(12).reshape(3,4)
M[1,2]      # element in row 1 col 2
M[0]        # first row
M[:, 1]     # second column

array([1, 5, 9])

- Views vs copies: slices are views (cheap); use `.copy()` to force a copy.

## **Fancy indexing (integer) & boolean indexing**

- Fancy indexing (creates copy):

In [25]:
arr = np.array([10,20,30,40,50])
arr[[0,2,4]]    # array([10,30,50])


array([10, 30, 50])

- Boolean indexing:

In [31]:
mask = arr > 25
arr[mask]       # array([30,40,50])
arr[arr % 20 == 0]  # elements divisible by 20


array([20, 40])

## **Shape manipulation**

- Reshape, ravel/flatten, transpose, expand_dims, squeeze:

In [40]:
a = np.arange(6)
a.reshape((2,3))
a.reshape(-1,1)   # infer dimension
a.ravel()         # view as 1D
a.flatten()       # copy as 1D
np.transpose(a.reshape(2,3))
np.expand_dims(a, axis=0)  # add new axis
np.squeeze(np.array([[[1],[2]]]))


array([1, 2])

## **Concatenation & splitting**

In [48]:
a = np.ones((2,2)); b = np.zeros((2,2))
np.concatenate([a,b], axis=0)   # stack vertically
np.vstack([a,b])
np.hstack([a,b])
np.split(np.arange(8), 4)       # 4 equal parts


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

## **Broadcasting**

Broadcasting lets arrays with different shapes work together using implicit expansion.

Rules: align trailing axes, dimensions equal or one of them is 1.

In [49]:
M = np.arange(6).reshape(2,3)
v = np.array([10,20,30])
M + v    # adds v to each row


array([[10, 21, 32],
       [13, 24, 35]])

## **Universal functions (ufuncs)**

Elementwise functions: `np.sin`, `np.exp`, `np.add`, `np.maximum`, etc.

In [54]:
np.sin(np.pi * np.linspace(0,1,5))
np.add([1,2,3], [4,5,6])
np.sqrt(np.array([1,4,9]))


array([1., 2., 3.])

## **Aggregations & axis argument**

- Sum, mean, min, max, std, var, argmin/argmax, cumulative ops:

In [68]:
M = np.arange(12).reshape(3,4)
M.sum()         # global sum
M.sum(axis=0)   # sum columns -> shape (4,)
M.mean(axis=1)  # mean per row
M.argmax()      # index of max in flattened array
np.cumsum([[1,2,3],[4,5,6]])   # cumulative sum


array([ 1,  3,  6, 10, 15, 21])

## **Random numbers**

Use `np.random` (recommended: `np.random.default_rng()` for new code):


In [75]:
rng = np.random.default_rng(42)
rng.random((2,3))   # floats in [0,1)
rng.integers(0, 10, size=5)
rng.normal(loc=0, scale=1, size=(3,))


array([-0.85304393,  0.87939797,  0.77779194])

## **Linear algebra**

For matrix multiplication use `@` in Python 3: `A @ B`.

In [76]:
A = np.array([[1.,2.],[3.,4.]])
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)
np.dot(A, np.array([1,2]))   # matrix-vector product

array([ 5., 11.])

## **Sorting, unique, comparisons**

In [79]:
np.sort([3,1,2])
np.argsort([3,1,2])
np.unique([1,2,2,3])

array([1, 2, 3])

## **Data types (dtype)**

Specify dtype or inspect/change it:

In [86]:

arr=np.array([1,2,3], dtype=np.float32)
arr.astype(np.int64)

array([1, 2, 3])

## **File I/O**

In [87]:
np.savetxt('arr.txt', np.arange(10))
np.loadtxt('arr.txt')
np.save('arr.npy', np.arange(10))       # binary
np.load('arr.npy')
np.savez('many.npz', a=np.arange(3), b=np.arange(4))

## Performance tips

- Prefer vectorized ops (ufuncs) over Python loops.
- Use built-in aggregations with `axis` param.
- Use appropriate `dtype` to reduce memory.
- Use `np.einsum` for complex tensor ops (careful: readability).

---
## Short Examples

1) Mean normalization of each column:

In [92]:
X = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
col_mean = X.mean(axis=0)
X_centered = X - col_mean    # broadcasting


2) Compute pairwise distances (Euclidean) between points (vectorized):

In [99]:
P = np.array([[0,0],[1,0],[1,1]])    # 3 points
# pairwise squared distances
diff = P[:, None, :] - P[None, :, :]
D2 = np.sum(diff**2, axis=-1)
D2


array([[0, 1, 2],
       [1, 0, 1],
       [2, 1, 0]])

3) Apply a mask to set negative values to zero:

In [102]:
a = np.array([-2, -1, 0, 1, 2])
a[a < 0] = 0


---
## **Practice Questions**

Try to solve these on your own; answers follow after the questions.

1. Create a 5x5 matrix with values 1..25 and extract the central 3x3 submatrix.


In [103]:
M = np.arange(1,26).reshape(5,5)
M[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

2. Given `a = np.arange(16)`, reshape to (4,4), then swap rows 0 and 3.

In [104]:
a = np.arange(16).reshape(4,4)
a[[0,3]] = a[[3,0]]   # swap using fancy indexing (works inplace)


3. Generate a 1D array of 20 random integers in [0,100). Compute the median.

In [105]:
rng = np.random.default_rng(0)
arr = rng.integers(0,100, size=20)
np.median(arr)


np.float64(57.5)

4. Given `A` shape (3,4) and `v` shape (4,), compute the row-wise dot product producing shape (3,).

In [106]:
result = A @ v    # or np.dot(A, v)
result


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

5. Create a boolean mask selecting elements of a 1D array that are prime numbers.

In [111]:

def is_prime(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True
arr = np.array([2,3,4,5,6,7,11,13])
mask = np.vectorize(is_prime)(arr)
arr[mask]


array([ 2,  3,  5,  7, 11, 13])

Note: For large arrays, there are faster sieve-based approaches; `np.vectorize` is convenience-only.